BilgiIslemEnvanter/Controllers/BirimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BilgiIslemEnvanter.Models.Entity;

namespace BilgiIslemEnvanter.Controllers
{
    public class BirimController : Controller
    {
        // GET: Birim
        private BilgiIslemEntities2 db = new BilgiIslemEntities2();
        [Authorize] 
        public ActionResult Index()
        {
            var liste = db.Birimler.Where(m => m.DURUM == true).ToList();
            return View(liste);
        }

        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Ekle(Birimler p)
        {
            if (!ModelState.IsValid)
            {
                return View("Ekle");
            }
            db.Birimler.Add(p);
            p.DURUM = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var bilgi = db.Birimler.Find(id);
            bilgi.DURUM = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Getir(int id)
        {
            var bilgi = db.Birimler.Find(id);
            return View("Getir", bilgi);
        }

        public ActionResult Guncelle(Birimler p)
        {
            var bilgi = db.Birimler.Find(p.ID);
            bilgi.BIRIMAD= p.BIRIMAD;
            bilgi.DURUM = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

BilgiIslemEnvanter/Views/Birim/Ekle.cshtml
@model BilgiIslemEnvanter.Models.Entity.Birimler

@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Ekle", "Birim", FormMethod.Post))
{


    <div class="col-md-6 col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Birimler Kayıt Formu</h4> 
            </div>
            <div class="card-content">
                <div class="card-body">
                    <form class="form form-horizontal">
                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <label>Birim Adı</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.BIRIMAD, new { @class = "form-control", @autofocus=""})
                                    @Html.ValidationMessageFor(m => m.BIRIMAD, "", new { @style = "color:red" })
                                </div>

                                

                                <div class="col-sm-12 d-flex justify-content-end">
                                    <button class="btn btn-primary mr-1 mb-1">Kayıt</button>

                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

}

BilgiIslemEnvanter/Views/Birim/Getir.cshtml
@model BilgiIslemEnvanter.Models.Entity.Birimler

@{
    ViewBag.Title = "Getir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Birim", FormMethod.Post))
{
    <div class="col-md-6 col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Birimler Kayıt Güncelleme Formu</h4>
            </div>
            <div class="card-content">
                <div class="card-body">
                    <form class="form form-horizontal">
                        <div class="form-body">
                            <div class="row">

                                <div class="col-md-4">
                                    <label>Birim ID</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.ID, new { @class = "form-control", @readonly = "readonly" })
                                </div>

                                <div class="col-md-4">
                                    <label>Birim Adı</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.BIRIMAD, new { @class = "form-control", @autofocus = "" })
                                </div>

                                
                                <div class="col-sm-12 d-flex justify-content-end">
                                    <button class="btn btn-primary mr-1 mb-1">Güncelle</button>

                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

BilgiIslemEnvanter/Views/Birim/Index.cshtml
@using BilgiIslemEnvanter.Models.Entity

@model List<BilgiIslemEnvanter.Models.Entity.Birimler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<a href="~/Birim/Ekle/" class="btn btn-primary">Birim Ekle</a>
<br />
<h2 style="color:red; text-align:center">Burdur Adliyesi Birimleri</h2>
<table id="veri" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr style="background: crimson; color: bisque">
            <td>ID</td>
            <td>BİRİM ADI</td>
            <td>İŞLEM</td>
        </tr>
    </thead>
    <tbody>
    @foreach (var bilgi in Model)
    {
        <tr>
            <th>@bilgi.ID</th>
            <td>@bilgi.BIRIMAD</td>
            <td>

                <a href="~/Birim/Sil/@bilgi.ID"><img border="0" alt="sil" src="~/resim/sil.png" width="20" height="20" /></a>
                <a href="~/Birim/Getir/@bilgi.ID"><img border="0" alt="sil" src="~/resim/update.png" width="20" height="20" /></a>
            </td>
        </tr>
    }
    </tbody>
</table>