BilgiIslemEnvanter/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BilgiIslemEnvanter.Models.Entity;
using Microsoft.Ajax.Utilities;

namespace BilgiIslemEnvanter.Controllers
{
    public class HomeController : Controller
    {
        private BilgiIslemEntities2 db = new BilgiIslemEntities2();
        [Authorize]
        public ActionResult Index()
        {
            var liste = db.TonerCikis.ToList();
            var kalantonerms510 = db.TonerStok.Where(i => i.YAZICIMARKALARIID == 1 && i.YAZICIMODELLERIID == 6).Sum(stok => stok.KALANTONER);
            ViewBag.dgr1 = kalantonerms510;

            var kalandrumms510= db.TonerStok.Where(i => i.YAZICIMARKALARIID == 1 && i.YAZICIMODELLERIID == 6).Sum(stok => stok.KALANDRUM);
            ViewBag.dgr2 = kalandrumms510;

            var kalantonerms810 = db.TonerStok.Where(i => i.YAZICIMARKALARIID == 1 && i.YAZICIMODELLERIID == 7).Sum(stok => stok.KALANTONER);
            ViewBag.dgr3 = kalantonerms810;

            var kalandrumms810 = db.TonerStok.Where(i => i.YAZICIMARKALARIID == 1 && i.YAZICIMODELLERIID == 7).Sum(stok => stok.KALANDRUM);
            ViewBag.dgr4 = kalandrumms810;

            var kalantonert650= db.TonerStok.Where(i => i.YAZICIMARKALARIID == 1 && i.YAZICIMODELLERIID == 10).Sum(stok => stok.KALANTONER);
            ViewBag.dgr5 = kalantonert650;

            var kalantonerms823 = db.TonerStok.Where(i => i.YAZICIMARKALARIID == 1 && i.YAZICIMODELLERIID == 8).Sum(stok => stok.KALANTONER);
            ViewBag.dgr6 = kalantonerms823;
            //var depopcsayisi = db.Bilgisayarlar.Where(i => i.ZIMMET == false).Count()-1;
            //ViewBag.dgr1 = depopcsayisi;
            //var yazicisayisi = db.Yazicilar.Where(i => i.ZIMMET == false).Count()-1;
            //ViewBag.dgr2 = yazicisayisi;
            //var tarayicisayisi = db.Tarayicilar.Where(i => i.ZIMMET == false).Count()-1;
            //ViewBag.dgr3 = tarayicisayisi;
            var kalantonermx710 = db.TonerStok.Where(i => i.YAZICIMARKALARIID == 1 && i.YAZICIMODELLERIID == 9).Sum(stok => stok.KALANTONER);
            ViewBag.dgr7 = kalantonermx710;

            var kalandrummx710 = db.TonerStok.Where(i => i.YAZICIMARKALARIID == 1 && i.YAZICIMODELLERIID == 9).Sum(stok => stok.KALANDRUM);
            ViewBag.dgr8 = kalandrummx710;



            return View(liste);


            
           
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

      
    }
}

BilgiIslemEnvanter/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BilgiIslemEnvanter.Models.Entity;
using BilgiIslemEnvanter.MyClasses;


namespace BilgiIslemEnvanter.Controllers
{
    public class PersonelController : Controller
    {
        // GET: Personel
        private BilgiIslemEntities2 db = new BilgiIslemEntities2();
        [Authorize]

        public ActionResult Index()
        {

            var liste = db.Personeller.Where(m => m.DURUM == true).ToList();
            return View(liste);
        }

        [HttpGet]
        public ActionResult Ekle()
        {
            List<SelectListItem> degerler1 = (from i in db.Unvanlar.Where(i => i.DURUM == true).ToList()
                                              select new SelectListItem
                                              {

                                                  Text = i.UNVANAD,
                                                  Value = i.ID.ToString(),

                                              }).ToList();
            ViewBag.dgr1 = degerler1;


            List<SelectListItem> degerler2 = (from i in db.Birimler.Where(i => i.DURUM == true).ToList()
                                              select new SelectListItem
                                              {

                                                  Text = i.BIRIMAD,
                                                  Value = i.ID.ToString(),

                                              }).ToList();
            ViewBag.dgr2 = degerler2;
            return View();
        }

        [HttpPost]
        public ActionResult Ekle(Personeller p)
        {


            var unvan = db.Unvanlar.Where(m => m.ID == p.Unvanlar.ID).FirstOrDefault();
            p.Unvanlar = unvan;
            var birim = db.Birimler.Where(m => m.ID == p.Birimler.ID).FirstOrDefault();
            p.Birimler = birim;
            if (p.SICIL == null)
            {
                return View("Ekle");
            }
            db.Personeller.Add(p);
            p.DURUM = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var bilgi = db.Personeller.Find(id);
            bilgi.DURUM = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Getir(int id)
        {
            List<SelectListItem> degerler1 = (from i in db.Unvanlar.Where(i => i.DURUM == true).ToList()
                                              select new SelectListItem
                                              {

                                                  Text = i.UNVANAD,
                                                  Value = i.ID.ToString(),

                                              }).ToList();
            ViewBag.dgr1 = degerler1;


            List<SelectListItem> degerler2 = (from i in db.Birimler.Where(i => i.DURUM == true).ToList()
                                              select new SelectListItem
                                              {

                                                  Text = i.BIRIMAD,
                                                  Value = i.ID.ToString(),

                                              }).ToList();
            ViewBag.dgr2 = degerler2;
            var bilgi = db.Personeller.Find(id);
            return View("Getir", bilgi);
        }

        public ActionResult Guncelle(Personeller p)
        {
            var bilgi = db.Personeller.Find(p.ID);
            bilgi.SICIL = p.SICIL;
            bilgi.ADSOYAD = p.ADSOYAD;
            bilgi.DAHILITELEFONU = p.DAHILITELEFONU;
            bilgi.CEPTELEFONU = p.CEPTELEFONU;
            bilgi.DURUM = true;
            var unvan = db.Unvanlar.Where(m => m.ID == p.Unvanlar.ID).FirstOrDefault();
            bilgi.UNVANID = unvan.ID;
            var birim = db.Birimler.Where(m => m.ID == p.Birimler.ID).FirstOrDefault();
            bilgi.BIRIMID = birim.ID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult ZimmetYap(int? ID)
        {
            ViewBag.id = ID;


            var BilgisayarModel = db.Bilgisayarlar.Where(x => x.DURUM == true && x.ZIMMET == false && x.SERINO != "BAKANLIK").OrderByDescending(x => x.SERINO == null).Select(a => new
            {
                Value = a.ID,
                Text = a.SERINO + " -- " + a.MARKA + " -- " + a.MODEL

            }).ToList();

            var YaziciModel = db.Yazicilar.Where(x => x.DURUM == true && x.ZIMMET == false).OrderByDescending(x => x.SERINO == null).Select(
                a => new
                {
                    Value = a.ID,

                    Text = a.SERINO + " -- " + a.YaziciMarkalari.YAZICIMARKA + " -- " + a.YaziciModelleri.YAZICIMODEL
                }).ToList();


            var TarayiciModel = db.Tarayicilar.Where(x => x.DURUM == true && x.ZIMMET == false).OrderByDescending(x => x.SERINO == null).Select(a => new
            {
                Value = a.ID,
                Text = a.SERINO + " -- " + a.MARKA + " -- " + a.MODEL
            }).ToList();

            ViewBag.tarayiciSN = new SelectList(TarayiciModel, "Value", "Text");
            ViewBag.yaziciSN = new SelectList(YaziciModel, "Value", "Text");
            ViewBag.BilgisayarSN = new SelectList(BilgisayarModel, "Value", "Text");





            return View();
        }

        [HttpPost]
        public ActionResult Zimmetle(HepiTopu hep)
        {

            var personel = hep.personelID;
            var yazici = hep.yaziciSN;
            var tarayici = hep.tarayiciSN;
            var bilgisayar = hep.bilgisayarSN;
            var domainadi = hep.domainAdi;
            var domainip = hep.domainIP;
            var yaziciip = hep.yaziciIP;
            var birim = hep.BirimID;
            hep.Durum = true;
            hep.Zimmet = true;


            Tasinirlar tasinir = new Tasinirlar
            {
                BILGISAYARID = bilgisayar,
                DOMAINADI = domainadi,
                DOMAINIP = domainip,
                PERSONELID = personel,
                TARAYICIID = tarayici,
                YAZICIID = yazici,
                YAZICIPORT = yaziciip,
                BIRIMID = birim, 
                DURUM = true,
                ZIMMET = true,

            };

            db.Tasinirlar.Add(tasinir);


            //Yazıcıyı Id ile buldu ve zimmet alanını true'ye çevirdi.
            var YaziciModel = db.Yazicilar.FirstOrDefault(x => x.ID == yazici);
            if (YaziciModel.SERINO == null)
            {
                YaziciModel.ZIMMET = false;
            }
            else 
            {
                YaziciModel.ZIMMET = true;
                YaziciModel.PERSONELID = hep.personelID;
                YaziciModel.BIRIMID = hep.BirimID;
            }
            db.Entry(YaziciModel).State = System.Data.Entity.EntityState.Modified;

            //Bilgisayar Id ile buldu ve zimmet alanını true'ye çevirdi.
            var BilgiModel = db.Bilgisayarlar.FirstOrDefault(x => x.ID == bilgisayar);
            if (BilgiModel.SERINO == null)
            {
                BilgiModel.ZIMMET = false;
            }
            else
            {
                BilgiModel.ZIMMET = true;
            }
            db.Entry(BilgiModel).State = System.Data.Entity.EntityState.Modified;

            //Tarayıcı Id ile buldu ve zimmet alanını true'ye çevirdi.
            var TaraModel = db.Tarayicilar.FirstOrDefault(x => x.ID == tarayici);
            if (TaraModel.SERINO == null)
            {
               TaraModel.ZIMMET = false;
            }
            else
            {
                TaraModel.ZIMMET = true;
            }
            db.Entry(TaraModel).State = System.Data.Entity.EntityState.Modified;


            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

BilgiIslemEnvanter/Controllers/TonerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BilgiIslemEnvanter.Models.Entity;

namespace BilgiIslemEnvanter.Controllers
{
    public class TonerController : Controller
    {
        // GET: Toner
        BilgiIslemEntities2 db = new BilgiIslemEntities2();
        [Authorize]

        public ActionResult Liste()
        {
            var listele = db.Yazicilar.Where(x => x.ZIMMET == true).ToList();
            return View(listele);
        }

        [HttpGet]
        public ActionResult TonerGiris()
        {
            List<SelectListItem> degerler1 = (from i in db.YaziciMarkalari.Where(i => i.DURUM == true).ToList()
                                              select new SelectListItem
                                              {

                                                  Text = i.YAZICIMARKA,
                                                  Value = i.ID.ToString(),

                                              }).ToList();
            ViewBag.dgr1 = degerler1;


            List<SelectListItem> degerler2 = (from i in db.YaziciModelleri.Where(i => i.DURUM == true).ToList()
                                              select new SelectListItem
                                              {

                                                  Text = i.YAZICIMODEL,
                                                  Value = i.ID.ToString(),

                                              }).ToList();
            ViewBag.dgr2 = degerler2;

            return View();
        }

        [HttpPost]
        public ActionResult TonerGiris(TonerGiris p)
        {


            var markasi = db.YaziciMarkalari.Where(m => m.ID == p.YaziciMarkalari.ID).FirstOrDefault();
            p.YaziciMarkalari = markasi;

            var modeli = db.YaziciModelleri.Where(m => m.ID == p.YaziciModelleri.ID).FirstOrDefault();
            p.YaziciModelleri = modeli;


            if (p.TONERADET == null)
            {
                return View("TonerGiris");
            }

            db.TonerGiris.Add(p);
            p.DURUM = true;


            //Bilgisayar Id ile buldu ve zimmet alanını true'ye çevirdi.
            var TonerEkle = db.TonerStok.FirstOrDefault(x =>
                x.YAZICIMARKALARIID == p.YAZICIMARKA && x.YAZICIMODELLERIID == p.YAZICIMODEL);
            TonerEkle.KALANTONER += p.TONERADET;
            TonerEkle.KALANDRUM += p.DRUMADET;
            db.Entry(TonerEkle).State = System.Data.Entity.EntityState.Modified;


            db.SaveChanges();
            return RedirectToAction("Liste");
        }

        [HttpGet]
        public ActionResult TonerCikis(int? ID)
        {

            ViewBag.id = ID;


            //var YaziciModel = db.Yazicilar.Where(x => x.ZIMMET == true).Select(a => new
            //{
            //    Value = a.ID,
            //    Text = a.SERINO

            var YaziciModel = db.Yazicilar.Where(x => x.ZIMMET == true).Select(a => new
            {
                Value = a.ID,
                Text = a.SERINO

            }).ToList();

            //ViewBag.dgr1 = YaziciModel;

            //List<SelectListItem> birimler = (from i in db.Birimler.Where(i => i.DURUM == true).ToList()
            //                                 select new SelectListItem
            //                                 {

            //                                     Text = i.BIRIMAD,
            //                                     Value = i.ID.ToString(),

            //                                 }).ToList();
            //ViewBag.dgr2 = birimler;


            //List<SelectListItem> personeller = (from i in db.Personeller.Where(i => i.DURUM == true).ToList()
            //                                    select new SelectListItem
            //                                    {

            //                                        Text = i.ADSOYAD,
            //                                        Value = i.ID.ToString(),

            //                                    }).ToList();
            //ViewBag.dgr3 = personeller;

            List<SelectListItem> kullanici = (from i in db.Kullanicilar.Where(i => i.DURUM == true).ToList()
                                              select new SelectListItem
                                              {

                                                  Text = i.ADISOYADI,
                                                  Value = i.ID.ToString(),

                                              }).ToList();
            ViewBag.dgr4 = kullanici;

            //List<SelectListItem> yazicimarka = (from i in db.YaziciMarkalari.Where(i => i.DURUM == true).ToList()
            //                                    select new SelectListItem
            //                                    {

            //                                        Text = i.YAZICIMARKA,
            //                                        Value = i.ID.ToString(),

            //                                    }).ToList();
            //ViewBag.dgr5 = yazicimarka;


            //List<SelectListItem> yazicimodel = (from i in db.YaziciModelleri.Where(i => i.DURUM == true).ToList()
            //                                    select new SelectListItem
            //                                    {

            //                                        Text = i.YAZICIMODEL,
            //                                        Value = i.ID.ToString(),

            //                                    }).ToList();
            //ViewBag.dgr6 = yazicimodel;


            return View();
        }

        [HttpPost]
        public ActionResult TonerCikis(TonerCikis toner)
        {


            if (ModelState.IsValid)
            {
                if (toner.TONERADET == null || toner.DRAMADET == null)
                {
                    return View("TonerCikis");
                }

                db.TonerCikis.Add(toner);


                var TonerCikar = db.TonerStok.FirstOrDefault(x =>
                    x.YAZICIMARKALARIID == toner.YAZICIMARKAID&& x.YAZICIMODELLERIID == toner.YAZICIMODELID);
                TonerCikar.KALANTONER -= toner.TONERADET;
                TonerCikar.KALANDRUM -= toner.DRAMADET;
                db.Entry(TonerCikar).State = System.Data.Entity.EntityState.Modified;

                db.SaveChanges();

            }

            return RedirectToAction("Liste");
        }
        
        public ActionResult TonerStok()
        {
            var model = db.TonerStok.ToList();
            return View(model);
        }
        
    }

}

BilgiIslemEnvanter/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BilgiIslemEnvanter/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BilgiIslemEnvanter/Views/Home/Index.cshtml
@using BilgiIslemEnvanter.Models.Entity
@model List<TonerCikis>
@{
    ViewBag.Title = "Home Page";
}

<main>
    <div class="container-fluid">
        <h1 class="mt-4" style="color: red; text-align: center">BURDUR BİLGİ İŞLEM ŞEFLİĞİ</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Gösterge Paneli</li> 
        </ol>
        <div class="row"> 
            <div class="col-xl-3 col-md-6">
                <div class="card bg-primary text-white mb-4">
                    <div class="card-body">Lexmark MS-510 Kalan Toner: @Html.ViewBag.dgr1</div>
                    <div class="card-body">Lexmark MS-510 Kalan Drum:  @Html.ViewBag.dgr2</div>
                    @*<div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" href="~/Toner/Toner/">Detay</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>*@
                </div>
            </div>
            <div class="col-xl-3 col-md-6">
                <div class="card bg-warning text-white mb-4">
                    <div class="card-body">Lexmark MS-810 Kalan Toner: @Html.ViewBag.dgr3</div>
                    <div class="card-body">Lexmark MS-810 Kalan Drum : @Html.ViewBag.dgr4</div>
                    @*<div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" href="~/Yazici/Index/">Detay</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>*@
                </div>
            </div>
            <div class="col-xl-3 col-md-6">
                <div class="card bg-success text-white mb-4">
                    <div class="card-body">Lexmark MX-710 Kalan Toner: @Html.ViewBag.dgr7</div>
                    <div class="card-body">Lexmark MX-710 Kalan Drum : @Html.ViewBag.dgr8</div>
                    @*<div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" href="~/Tarayici/Index">Detay</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>*@
                </div>
            </div>
            <div class="col-xl-3 col-md-6">
                <div class="card bg-danger text-white mb-4">
                    <div class="card-body">Lexmark T650 Kalan Toner  : @Html.ViewBag.dgr5</div>
                    <div class="card-body">Lexmark MS-823 Kalan Toner: @Html.ViewBag.dgr6</div>
                    @*<div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" href="~/Personel/Index">Detay</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>*@
                </div>
            </div>
        </div>
        @*<div class="row">
                <div class="col-xl-6">
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-chart-area mr-1"></i>
                            Area Chart Example
                        </div>
                        <div class="card-body"><canvas id="myAreaChart" height="40"></canvas></div>
                    </div>
                </div>
                <div class="col-xl-6">
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-chart-bar mr-1"></i>
                            Bar Chart Example
                        </div>
                        <div class="card-body"><canvas id="myBarChart" height="40"></canvas></div>
                    </div>
                </div>
            </div>*@




        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1" style="color: red"></i>
                @*<b><label style="color:red">Toner Çıkışı Yapılan Birimler</label></b>*@
                <a class="btn btn-primary" href="@Url.Action("Liste","Toner")">TONER ÇIKIŞ</a>
                <a class="btn btn-warning" href="@Url.Action("TonerStok","Toner")">TONER STOK</a>
                <a class="btn btn-danger" href="@Url.Action("ZimmetListesi","Raporlar")">ZİMMET LİSTESİ</a>
                <a class="btn btn-success" href="@Url.Action("Index","Personel")">REHBER</a>
                @*<a class="btn btn-success" href="@Url.Action("Yedekleme","Home")">VERİTABANI YEDEKLE</a>*@
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr style="background: darkred; color: white">
                                <th>Kullanıcı</th>
                                <th>Birimi</th>
                                <th>Yazıcı Marka</th>
                                <th>Yazıcı Model</th>
                                <th>Veriliş Tarihi</th>
                                <th>Takan Personel</th>
                                <th>Toner/Drum</th>
                            </tr>
                        </thead>

                        @foreach (var item in Model)
                        {
                            <tbody>
                                <tr>
                                    <td>@item.Yazicilar.Personeller.ADSOYAD</td>
                                    <td>@item.Birimler.BIRIMAD</td>
                                    <td>@item.YaziciMarkalari.YAZICIMARKA</td>
                                    <td>@item.YaziciModelleri.YAZICIMODEL</td>
                                    <td>@Convert.ToDateTime(item.TAKMATARIHI).ToString("d")</td>
                                    <td>@item.Kullanicilar.ADISOYADI</td>
                                    @if (item.DRAMADET == 0)
                                    {
                                        <td style="color: red">TONER</td>
                                    }
                                    else
                                    {
                                        <td style="color: blue">DRUM</td>
                                    }


                                </tr>
                            </tbody>

                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
</main>