BilgiIslemEnvanter/Controllers/YaziciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BilgiIslemEnvanter.Models.Entity;

namespace BilgiIslemEnvanter.Controllers
{
    public class YaziciController : Controller
    {
        // GET: Yazici

        private BilgiIslemEntities2 db = new BilgiIslemEntities2();
        [Authorize]
        public ActionResult Index()
        {
            var listeleme = db.Yazicilar.Where(i=>i.DURUM==true).ToList();
            //var liste = db.Yazicilar.Where(m => m.DURUM == true).ToList();
            return View(listeleme);
        }

        [HttpGet]
        public ActionResult Ekle()
        {
            List<SelectListItem> degerler1 = (from i in db.YaziciMarkalari.Where(i => i.DURUM == true).ToList()
                                              select new SelectListItem
                                              {

                                                  Text = i.YAZICIMARKA,
                                                  Value = i.ID.ToString(),

                                              }).ToList();
            ViewBag.dgr1 = degerler1;


            List<SelectListItem> degerler2 = (from i in db.YaziciModelleri.Where(i => i.DURUM == true).ToList()
                                              select new SelectListItem
                                              {

                                                  Text = i.YAZICIMODEL,
                                                  Value = i.ID.ToString(),

                                              }).ToList();
            ViewBag.dgr2 = degerler2;

            return View();

        }

        [HttpPost]
        public ActionResult Ekle(Yazicilar p)
        {
            if (!ModelState.IsValid)
            {
                return View("Ekle");
            }
            
            p.DURUM = true;
            p.ZIMMET = false;
            p.BIRIMID = 50;
            p.PERSONELID = 176;
            
            db.Yazicilar.Add(p);
            
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var bilgi = db.Yazicilar.Find(id);
            bilgi.DURUM = false;
            bilgi.ZIMMET = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Getir(int id)
        {
            var bilgi = db.Yazicilar.Find(id);
            return View("Getir", bilgi);
        }

        public ActionResult Guncelle(Yazicilar p)
        {
            var bilgi = db.Yazicilar.Find(p.ID);


            var yazicimarkasi= db.YaziciMarkalari.Where(m => m.ID == p.YaziciMarkalari.ID).FirstOrDefault();
            bilgi.MARKAID= p.YaziciMarkalari.ID;

            var yazicimodels = db.YaziciModelleri.Where(m => m.ID == p.YaziciModelleri.ID).FirstOrDefault();
            bilgi.MODELID = p.YaziciModelleri.ID;

            bilgi.MARKAID = p.MARKAID;
            bilgi.MODELID = p.MODELID;

            bilgi.SERINO = p.SERINO;
            bilgi.DURUM = true;
            bilgi.ZIMMET = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BilgiIslemEnvanter/Views/Yazici/Ekle.cshtml
@model BilgiIslemEnvanter.Models.Entity.Yazicilar

@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Ekle", "Yazici", FormMethod.Post))
{


    <div class="col-md-6 col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Yazıcı Kayıt Formu</h4>
            </div>
            <div class="card-content">
                <div class="card-body">
                    <form class="form form-horizontal">
                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <b><label>Yazıcı Marka</label></b>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.DropDownListFor(m => m.MARKAID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control", @name="MARKAID" })
                                </div>
                                <div class="col-md-4">
                                    <b><label>Yazıcı Model</label></b>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.DropDownListFor(m => m.MODELID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control", @name = "MODELID" })
                                </div>

                                <div class="col-md-4">
                                    <label>Seri No</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.SERINO, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.SERINO, "", new { @style = "color:red" })
                                </div>

                                <div class="col-sm-12 d-flex justify-content-end">
                                    <button class="btn btn-primary mr-1 mb-1">Kayıt</button>

                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

}

BilgiIslemEnvanter/Views/Yazici/Getir.cshtml
@model BilgiIslemEnvanter.Models.Entity.Yazicilar

@{
    ViewBag.Title = "Getir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Yazici", FormMethod.Post))
{
    <div class="col-md-6 col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Yazıcı Kayıt Güncelleme Formu</h4>
            </div>
            <div class="card-content">
                <div class="card-body">
                    <form class="form form-horizontal">
                        <div class="form-body">
                            <div class="row">

                                <div class="col-md-4">
                                    <label>Yazıcı ID</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.ID, new { @class = "form-control", @readonly = "readonly" })
                                </div>

                                <div class="col-md-4">
                                    <label>Markası</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.YaziciMarkalari.YAZICIMARKA, new { @class = "form-control", @autofocus = "" })
                                </div>

                                <div class="col-md-4">
                                    <label>Modeli</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.YaziciModelleri.YAZICIMODEL, new { @class = "form-control" })
                                </div>

                                <div class="col-md-4">
                                    <label>Seri Numarası</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.SERINO, new { @class = "form-control" })
                                </div>

                                <div class="col-sm-12 d-flex justify-content-end">
                                    <button class="btn btn-primary mr-1 mb-1">Güncelle</button>

                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

BilgiIslemEnvanter/Views/Yazici/Index.cshtml
@using BilgiIslemEnvanter.Models.Entity
@model List<Yazicilar>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<a href="~/Yazici/Ekle/" class="btn btn-primary">Yazıcı Ekle</a>
<br />

<h2 style="color:red; text-align:center">Burdur Adliyesine ait Yazıcı Listesi</h2>


<table id="veri" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr style="background: crimson; color: bisque">

            <td>
                ID
            </td>

            <td>
                MARKA
            </td>
            <td>
                MODEL
            </td>
            <td>
                SERİ NO
            </td>
            <td>
                İŞLEM
            </td>

        </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.YaziciMarkalari.YAZICIMARKA)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.YaziciModelleri.YAZICIMODEL)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SERINO)
                </td>
                <td>
                    <a href="~/Yazici/Sil/@item.ID"><img border="0" alt="sil" src="~/resim/sil.png" width="20" height="20" /></a>
                    <a href="~/Yazici/Getir/@item.ID"><img border="0" alt="sil" src="~/resim/update.png" width="20" height="20" /></a>
                </td>

            </tr>
        }
    </tbody>
</table>



@*<table id="veri" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <td>ID</td>
                <td>MARKA</td>
                <td>MODEL</td>
                <td>SERİ NO</td>
                <td>İŞLEM</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var yazici in Model)
            {
                <tr>
                    <th>@yazici.ID</th>
                    <td>@yazici.YaziciMarkalari.YAZICIMARKA</td>
                    <td>@yazici.YaziciModelleri.YAZICIMODEL</td>
                    <td>@yazici.SERINO</td>
                    <td>

                        <a href="/Yazici/Sil/@yazici.ID"><img border="0" alt="sil" src="~/resim/sil.png" width="20" height="20" /></a>
                        <a href="/Yazici/Getir/@yazici.ID"><img border="0" alt="sil" src="~/resim/update.png" width="20" height="20" /></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>*@