BilgiIslemEnvanter/Controllers/TarayiciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BilgiIslemEnvanter.Models.Entity;

namespace BilgiIslemEnvanter.Controllers
{
    public class TarayiciController : Controller
    {
        // GET: Tarayici
        private BilgiIslemEntities2 db = new BilgiIslemEntities2();
        [Authorize]
        public ActionResult Index()
        {
            var liste = db.Tarayicilar.Where(m => m.DURUM == true).ToList();
            return View(liste);
        }

        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Ekle(Tarayicilar p)
        {
            if (!ModelState.IsValid)
            {
                return View("Ekle");
            }
            db.Tarayicilar.Add(p);
            p.DURUM = true;
            p.ZIMMET = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var bilgi = db.Tarayicilar.Find(id);
            bilgi.DURUM = false;
            bilgi.ZIMMET = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Getir(int id)
        {
            var bilgi = db.Tarayicilar.Find(id);
            return View("Getir", bilgi);
        }

        public ActionResult Guncelle(Tarayicilar p)
        {
            var bilgi = db.Tarayicilar.Find(p.ID);
            bilgi.MARKA = p.MARKA;
            bilgi.MODEL = p.MODEL;
            bilgi.SERINO = p.SERINO;
            bilgi.DURUM = true;
            bilgi.ZIMMET = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BilgiIslemEnvanter/Views/Tarayici/Ekle.cshtml
@model BilgiIslemEnvanter.Models.Entity.Tarayicilar

@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Ekle", "Tarayici", FormMethod.Post))
{


    <div class="col-md-6 col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Tarayıcı Kayıt Formu</h4>
            </div>
            <div class="card-content">
                <div class="card-body">
                    <form class="form form-horizontal">
                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <label>Marka</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.MARKA, new { @class = "form-control", @autofocus="" })
                                    @Html.ValidationMessageFor(m => m.MARKA, "", new { @style = "color:red" })
                                </div>

                                <div class="col-md-4">
                                    <label>Model</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.MODEL, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.MODEL, "", new { @style = "color:red" })
                                </div>

                                <div class="col-md-4">
                                    <label>Seri No</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.SERINO, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.SERINO, "", new { @style = "color:red" })
                                </div>

                                <div class="col-sm-12 d-flex justify-content-end">
                                    <button class="btn btn-primary mr-1 mb-1">Kayıt</button>

                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

}

BilgiIslemEnvanter/Views/Tarayici/Getir.cshtml
@model BilgiIslemEnvanter.Models.Entity.Tarayicilar

@{
    ViewBag.Title = "Getir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Tarayici", FormMethod.Post))
{
    <div class="col-md-6 col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Tarayıcı Kayıt Güncelleme Formu</h4>
            </div>
            <div class="card-content">
                <div class="card-body">
                    <form class="form form-horizontal">
                        <div class="form-body">
                            <div class="row">

                                <div class="col-md-4">
                                    <label>Tarayıcı ID</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.ID, new { @class = "form-control", @readonly = "readonly" })
                                </div>

                                <div class="col-md-4">
                                    <label>Markası</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.MARKA, new { @class = "form-control", @autofocus = "" })
                                </div>

                                <div class="col-md-4">
                                    <label>Modeli</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.MODEL, new { @class = "form-control" })
                                </div>

                                <div class="col-md-4">
                                    <label>Seri Numarası</label>
                                </div>
                                <div class="col-md-8 form-group">
                                    @Html.TextBoxFor(m => m.SERINO, new { @class = "form-control" })
                                </div>

                                <div class="col-sm-12 d-flex justify-content-end">
                                    <button class="btn btn-primary mr-1 mb-1">Güncelle</button>

                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

BilgiIslemEnvanter/Views/Tarayici/Index.cshtml
@using BilgiIslemEnvanter.Models.Entity
@model List<Tarayicilar>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<a href="~/Tarayici/Ekle/" class="btn btn-primary">Tarayıcı Ekle</a>
<br />
<h2 style="color:red; text-align:center">Burdur Adliyesine ait Tarayıcı Listesi</h2>

<table id="veri" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr style="background: crimson; color: bisque">
            <td>ID</td>
            <td>MARKA</td>
            <td>MODEL</td>
            <td>SERİ NO</td>
            <td>İŞLEM</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var bilgi in Model)
        {
            <tr>
                <th>@bilgi.ID</th>
                <td>@bilgi.MARKA</td>
                <td>@bilgi.MODEL</td>
                <td>@bilgi.SERINO</td>
                <td>

                    <a href="~/Tarayici/Sil/@bilgi.ID"><img border="0" alt="sil" src="~/resim/sil.png" width="20" height="20" /></a>
                    <a href="~/Tarayici/Getir/@bilgi.ID"><img border="0" alt="sil" src="~/resim/update.png" width="20" height="20" /></a>
                </td>
            </tr>
        }
    </tbody>
</table>